### ISSUE TITLE
[Bug] Application freezes

### ISSUE THREAD

**Issue by Virus288** [ccgauche/ytermusic#100]
Env: Arch linux

Build method: Aur ( also tried manually )

Whats happening: Application freezes as soon as at least 1 song is downloaded. Local playback also freezes application

What did I expect to happend: To download and play songs

When did it occur: Around a year ago out of the blue. Did not update nor anything. While "debugging", I saw a pattern. If ytermusic downloads older songs, everything is working. As soon as it manages to download anything never ( few years ), it freezes. Cannot reproduce this now. Might be just my imagination.

Logs:
[log.txt](https://github.com/user-attachments/files/16911029/log.txt)

**Comment by AndrePssoa** [comment]
Same problem here.
I'm using Manjaro.

**Comment by ccgauche** [comment]
Do you have the same issue while building from the GH repo ?

**Comment by Virus288** [comment]
@ccgauche Yes. I just built this app with cargo from source and still freezes. Only error in logs is 
```log
ERROR - probe reach EOF at 0 bytes. [/home/virus288/.cargo/git/checkouts/symphonia-8fbe6c90fc095688/4f41954/symphonia-core/src/probe.rs]
```

If you'll need some1 to test stuff, you can mark me ;)

**Comment by luapDDas** [comment]
I've been having the same issue, I'm not sure what the difference is, but I either get the #96 issue with some songs, or the full system freeze with others.
I tested with type o negative - black no. 1 (https://music.youtube.com/watch?v=JmijMVT3x-0) and that instantly freezes, same probe.rs error message.

**Comment by Virus288** [comment]
Thats the playlist I am downloading. Ytermusic shows that 5 songs are downloaded. I assume 5 from the top https://www.youtube.com/watch?v=oEM2M15Ypfw&list=PLhCAPpVUinTCLrE77JMzldvGRsDy1vX5I

**Comment by abaudhuin** [comment]
First time user, I have this issue with every songs

**Comment by Lite5h4dow** [comment]
same issue, nixos.

**Comment by zalakGoat** [comment]
Having the same issue on EndeavourOS.

**Comment by ccgauche** [comment]
Can someone try deleting the Cargo.toml file and fetching from master to see if it works ?

**Comment by ccgauche** [comment]
I think it was fixed in the last rusty-ytdl

**Comment by Virus288** [comment]
@ccgauche I just built it. My older config was invalid so I've added new cookie. I think that something changed in cookies, or your app changed something, because I keep on geting 
```
ERROR - The `/home/virus288/.config/ytermusic/headers.txt` file is not configured correctly.
```

Full log

```
INFO - Logger mode INFO [src/systems/logger.rs]
INFO - Init: 0ms [src/structures/performance.rs]
INFO - Startup: 0ms [src/structures/performance.rs]
INFO - Spawned clean task: 0ms [src/structures/performance.rs]
INFO - Loading config from "/home/virus288/.config/ytermusic/config.toml" [src/config.rs]
INFO - Clean task: 0ms [src/structures/performance.rs]
INFO - Spawned system task: 10ms [src/structures/performance.rs]
INFO - Spawned last playlist task: 10ms [src/structures/performance.rs]
INFO - Spawned api task: 10ms [src/structures/performance.rs]
INFO - Running manager: 10ms [src/structures/performance.rs]
INFO - Last playlist task on [src/tasks/last_playlist.rs]
INFO - Last playlist: 0ms [src/structures/performance.rs]
INFO - API task on [src/tasks/api.rs]
INFO - Database getter task on [src/tasks/local_musics.rs]
INFO - Local musics: 0ms [src/structures/performance.rs]
ERROR - The `/home/virus288/.config/ytermusic/headers.txt` file is not configured correctly.
The cookies are expired or invalid. [src/tasks/api.rs]
ERROR - InvalidCookie [src/tasks/api.rs]
INFO - API task: 1129ms [src/structures/performance.rs]
```

**Comment by ccgauche** [comment]
I fixed the issue but be sure to enable raw mode for copying most of the time I had this issue it was because I copied the preview of the cookies which contains an UTF8 character (…) @Virus288

**Comment by Virus288** [comment]
It seems that for whatever reason, cookies from firefox ( librewolf ) are invalid. Cookies from chrome are working, which is strange, but google likes blocking people for fun...

Anyway. Seems to be working fine how. Huge thanks for fix <3 .
