### ISSUE TITLE
Add searching for albums, artists, playlists 

### ISSUE THREAD

**Issue by ccgauche** [ccgauche/ytermusic#11]

**Comment by Alphare** [comment]
I do most of my listening on albums and this would be very much appreciated.

**Comment by ccgauche** [comment]
9562ffb0a8e03a401b78ca389fc0d9eaed86bcbf Playlist and albums can now be searched

**Comment by ccgauche** [comment]
It was caused by an issue in the API:
 - Youtube says to my API that Playlists and Albums are the same
 - But don't include the Author nor the album in the video list so it fails to get the video expecting a title
 - I had to create a new extractor for albums 6363b31c43dc35f677c6e58c6a1a710aac3655e5

**Comment by ccgauche** [comment]
> Playlists and albums should be differentiated so it's more obvious which are official

A little complicated but achievable

>Albums should be sorted by album list unless explicitly shuffled (we should probably add like a "Shift+s" shortcut to "un-shuffule" also)

This would reduce responsiveness

> Downloaded albums should be browsable from the playlist view, possibly in a separate section?
This is linked with #12 

> Downloaded albums should be searchable and marked as local in the search view

Also kind of linked with #12 but adding some sort of saved playlist / albums could be a good idea

**Comment by Alphare** [comment]
> > Albums should be sorted by album list unless explicitly shuffled (we should probably add like a "Shift+s" shortcut to "un-shuffule" also)
> 
> This would reduce responsiveness

Yes, but it's fine in the case of an album. I see three use-cases for search by album:

- Either you want to listen to the whole thing as intended, in which case you need the first song of the album to start playing and the others to follow in order
- Or you remember the album name and want to listen to / start with a specific song, in which case you want that song to start playing and not just the first one that downloads
- Or you want to listen to it on shuffle, in which case you can just shuffle at will

In any case, even playlists do have an order that's intended by the creator (think DJs or just mood-setting), so random order isn't a good default IMO.

**Comment by ccgauche** [comment]
@Alphare If the playlist is already downloaded then it will play in order.
The thing is I start download tasks that finished when they finish and push to the queue I can't make them wait the one on the other. A good option would be to limit the number of download threads to 1.

**Comment by Alphare** [comment]
One way of making this work would be to define a "in-order" mode for the music player:

-  Assuming it knows all of the songs in the playlist/album (true for albums, not sure for playlists?)
- Shows this list, marking non-downloaded songs as such until they are downloaded
- Waits for the song that was picked by the user to be downloaded to start playing

That way you have a consistent display, a consistent listening experience, and still fast concurrent downloads. If the picked song is forced as part of the first batch of concurrent downloads, then it's a good chance that the user doesn't have to wait too much at all.

Does that make sense?

**Comment by ccgauche** [comment]
Yep definetly an option but what I would do would be:
 - All the musics are either in white (downloaded)
 - Blue (downloading)
 - Grey (waiting to be downloaded)
And always in order so they start to play when they are downloaded.
If in grey or blue the player waits for them to be white

**Comment by ccgauche** [comment]
@Alphare The latest commit fixed the issue. Now musics are in order with still concurrent download + musics that fail to get downloaded are show with an error icon.

**Comment by Alphare** [comment]
That does seem to work great, thanks a lot!
