### ISSUE TITLE
No content displayed on TUI

### ISSUE THREAD

**Issue by Karrq** [ccgauche/ytermusic#15]
Hi, awesome project! I was really looking for a proper yt music api with offline caching program, so, thanks!

Unfortunately, when I run the program (built from source) nothing is populated in the TUI.
I looked at the log file and found only a single line (which is [this song](https://music.youtube.com/watch?v=IxhEmfxVax8&feature=share)):
```
InvalidJsonCantFind("navigationEndpoint", "{\"text\":\"In Heat (feat. Hentai Xander)\"}")
```

**Comment by ccgauche** [comment]
That's an issue with the API... Somehow it is not able to parse the JSON which seems different. I expected some problems like that would happen with the current "rough" API. I'm working on a fix.

**Comment by ccgauche** [comment]
@Karrq some fixes to the API where made to make it more resistant to variations in the API output can you check weather the last commit fixes your issue?

**Comment by Alphare** [comment]
This fixed the issue for me at least. :)

**Comment by ccgauche** [comment]
I'll reopen the issue if needed
