### ISSUE TITLE
Wierd compression artifacts on some downloads

### ISSUE THREAD

**Issue by Alphare** [ccgauche/ytermusic#18]
I'm not 100% sure how to reproduce this, but when trying out the basic functionality, I got at least one song with weird compression artifacts for a couple of seconds (sounds like it's underwater in one ear).

A workaround would be to allow resetting the cache for a given song/album (when album support is available), which I think is always a good option to have. :)

**Comment by ccgauche** [comment]
The compression artifacts are from an issue in Symphonia on the AAC decoder. https://github.com/pdeljanov/Symphonia/issues/151
I just need to update the backend
