### ISSUE TITLE
First time use is confusing

### ISSUE THREAD

**Issue by Alphare** [ccgauche/ytermusic#21]
I've updated to the latest version (which changed where my caches are, which I'm not complaining about, this was a good change), and now I can't really figure out what the intended way of getting music to play is.

After a random amount of clicking and spacebar action it stars playing, but there is no clear indication of why.

**Comment by ccgauche** [comment]
The issue is that while music is downloading it can't be played. You should see your musics written in blue (being downloaded) so it's probably not the action repetition but the time it takes to download the first musics (When the cache grows there is pretty much always music already downloaded so no issue). 
Correct me if I'm missing the point and maybe send a screenshot

**Comment by Karrq** [comment]
I had the same experience, indeed after a while the songs were downloaded and I could play them.
I tried looking where they were saved but the `data` folder seemed empty, so I tried restarting the application and the TUI won't display like before....

**Comment by ccgauche** [comment]
The data folder has been moved in your appdata directory to be more consistent with others apps.
But the fact restarting the TUI breaks things is strange.

**Comment by Karrq** [comment]
Ok the TUI works now, maybe I didn't wait long enough or something

**Comment by ccgauche** [comment]
It's not expected to be waiting for the TUI to load it's definitely an issue. What system are you using ? What specs ?

**Comment by Karrq** [comment]
I'm on Arch with my Zephyrus G14 2022, so Ryzen 9 5900HS and 32GB of RAM...

**Comment by ccgauche** [comment]
Yep so no chance this comes from a performance issue on the computer side. Maybe something related to arch. Anyways I plan on adding a performance meter for startup tasks. (This can be linked to tokio waiting for some tasks to finish before starting others)

**Comment by Alphare** [comment]
> The issue is that while music is downloading it can't be played. You should see your musics written in blue (being downloaded) so it's probably not the action repetition but the time it takes to download the first musics (When the cache grows there is pretty much always music already downloaded so no issue). Correct me if I'm missing the point and maybe send a screenshot

I see. It's unclear to the user what is happening, since there is no sense of priority: which song will start playing first? Can I act on it?
There is also no indication of progress, at least for me, contributes to the feeling of being stuck.

Related, do you think streaming the requested song so we could have instant playback would be possible in the future?

**Comment by ccgauche** [comment]
Adding a progress percentage or some animation could be a good idea. The playlist gets shuffled thhen played so no way of knowing which song plays first. 
Streaming music is not possible with the current Symphonia ACC decoder...

**Comment by ccgauche** [comment]
@Karrq I added some performance measurements can you reproduce the problem and send the log

**Comment by ccgauche** [comment]
@Alphare I've added some progress percentage information in the last commit 8715a7f4226333dcdac1ebafd5d1eabfc4de19de

**Comment by Alphare** [comment]
> @Alphare I've added some progress percentage information in the last commit [8715a7f](https://github.com/ccgauche/ytermusic/commit/8715a7f4226333dcdac1ebafd5d1eabfc4de19de)

Thanks! This is very useful to make the experience less confusing: it is now very clear that (at least in my case) 4 songs are being downloading concurrently and that nothing is happening because of this.
