### ISSUE TITLE
Search should be debounced

### ISSUE THREAD

**Issue by Alphare** [ccgauche/ytermusic#22]
Currently, searching triggers an API call for (almost?) each keystroke, which pollutes the (google account) search history on top of being wasteful of resources. The local results maybe could still be matched on each keystroke given that there is no search history nor real performance issues.

A debounce of 150-200ms is usually a good bet?

(I'm writing this issue as I come across it, I will take time to answer the other issue I've opened. :) )

**Comment by ccgauche** [comment]
Yep I can add a debounce 200ms will probably be imperceptible. (It does trigger for each keystroke but if you type fast the previous request gets cancelled before reaching the host)

**Comment by Alphare** [comment]
I'm not sure that counting on winning a race condition is the most robust way of going about this? Or maybe I misunderstood what you mean.

**Comment by ccgauche** [comment]
I didn't say the current system is good and I should definitely change it. (It's really easy to fix furthermore)

**Comment by ccgauche** [comment]
77bdf2a7e9eb3bbdfd411f35e076810b91c38b5c FIXED
