### ISSUE TITLE
Separate scrolling in music player view from the currently playing song

### ISSUE THREAD

**Issue by Alphare** [ccgauche/ytermusic#26]
Thanks for implementing scrolling. :)

Scrolling in music player view still triggers `SoundAction::Previous(1).apply_sound_action(self);` or ``SoundAction::Next(1).apply_sound_action(self);``, making it impossible to scroll through the playlist without changing the current song, something I personally do a lot.

A separate counter should be kept for the "currently selected" and "currently playing", offering a similar interface to the playlist view.

**Comment by ccgauche** [comment]
Fixed in 7c95c7db2b3e72e9afaa2a5f349e026896b074f7 @Alphare @besuper

**Comment by Alphare** [comment]
It works great, thanks a lot! `ytermusic` is getting closer and closer to filling most of my needs. :)
