### ISSUE TITLE
can't load playlists from music.youtube.com anymore

### ISSUE THREAD

**Issue by vitalije** [ccgauche/ytermusic#33]
I've been using ytermusic for some time. Today I've added (using browser) some new songs to one of my playlists. When I restarted ytermusic (in order to refresh the content of my playlist), it now shows only two items

   1. last played playlist which contains old data and 
   2. local music

There used to be along with those two items several others playlists and albums, but now they are all gone.

Maybe Google has changed something in their data format.

**Comment by ccgauche** [comment]
The protocol error is quite strange have you changed anything ? I remember this happening when switching from openssl to rust-tls. Offline playlist are a pending feature don't worry about this. (This last playlist things is sort of a dirty fix).
Have you tried reloading your cookies?

**Comment by ccgauche** [comment]
@vitalije It's really strange. Furthermore it doesn't seems like this error is a known issue with hyper it's maybe due to your local youtube-music server being on a slightly different version. 
Anyways I updated the error reporting to use Display instead of debug and maybe find some known issue.
Can you run the app again and send the log file.

**Comment by vitalije** [comment]
With the latest 9ab0f388eea58411, log.txt looks like:
```
# YTerMusic log file

[PERF] Init: 0ms
[PERF] Startup: 0ms
[PERF] Spawned clean task: 0ms
[PERF] Clean task: 0ms
[PERF] Spawned system task: 4ms
[PERF] Spawned last playlist task: 4ms
[PERF] Spawned api task: 4ms
[PERF] Running manager: 4ms
Last playlist task on
Database getter task on
[PERF] Last playlist: 0ms
API task on
[PERF] Local musics: 0ms
Reqwest error: request or response body error: error reading a body from connection: stream error received: unspecific protocol error detected
[PERF] API task: 75ms
```

**Comment by ccgauche** [comment]
Extremely strange it could be caused by so many issues ... I remember having this issue when switching from openssl to rust-tls but somehow it magically disappeared. Maybe you can try switching back to openSSL (in the ytapi crate at least)

**Comment by vitalije** [comment]
How am I going to do that?

I see in the Cargo.toml there is "rustls-tls" feature set for rustube dependency. Should I change it to something else?

**Comment by ccgauche** [comment]
I updated reqwest and tokio in the case it was fixed recently.
If my last commit doesn't work just remove the "rustls-tls" feature in ytapi/Cargo.toml

**Comment by vitalije** [comment]
Changing `rustls-tls` to `native-tls` in Cargo.toml, produced another error (Invalid HTML file) in the log.txt. 
Logged value of invalid html file was binary. My browser has header:
```
Accept-Encoding: gzip, deflate, br
```
and apparently the document was encoded using brotli compression. When I removed `br` from the list of acceptable encodings, variant with `native-tls` feature worked, but variant with `rustls-tls` feature didn't.

So, in order to fix this issue, I had to:
1. remove `br` from the `Accept-Encoding` header in headers.txt
2. change selected feature `rustls-tls` to `native-tls` and rebuild

and now I'm seeing again all my playlists along with recommended playlists.

Thanks for your help and thanks for creating this beautiful tool.

**Comment by ccgauche** [comment]
Oh I see you copied all your headers.... It's only be mean in the case youtube-music adds some anti-bot tools using header validation. You should ONLY copy your cookies for now maybe I should add a warning in the installation process

**Comment by ccgauche** [comment]
Or force Accept-Encoding to deflate and bzip

**Comment by vitalije** [comment]
I used to have only `Cookie` header in the `headers.txt`, but when I started to have problems (missing playlists), I thought that maybe it needed other headers too, so I copied them all.

I don't know if it is possible to eliminate this `headers.txt` trick and simulate full communication with the server. I see that it is possible to open public playlist in the private browsing mode (without any login) and the content of the playlist is visible. So, Google actually doesn't require user to be logged in to show public playlist.

Maybe after first request to `YTMDOMAIN` with no cookie at all, server will respond with the set-cookie header, and this header can be captured instead of asking user to copy value from the browser and put it in the `headers.txt` file.

**Comment by ccgauche** [comment]
Thank you for helping improve `ytermusic`. If you have any other problem or suggestion to improve the app please fill up an issue. (Your offline playlist thing will definitely be added)
Youtube Music doesn't require cookies to get access to youtube music those are only necessary when you want to play your own playlists / songs from your library.
If `ytermusic` requires cookies, it is that I don't see a point using it just to search music but in the future it could be an option that I will definitely consider

**Comment by ccgauche** [comment]
This app has originally made for my own use and hasn't been create with the purpose of being a fully-fledged youtube music desktop client even if it is getting closer and closer.
