### ISSUE TITLE
API seems to not work anymore?

### ISSUE THREAD

**Issue by Alphare** [ccgauche/ytermusic#47]
I've just come back from a work trip so this might be ~a week old, but the online features of `ytermusic` do not seem to work anymore. The only playlists showing up are the "last playlist" and "local musics" (sic), and the search is only looking for local songs.

I've updated my `Cookie` header, but it doesn't work either. Was there a change in the API?

**Comment by ccgauche** [comment]
Yep youtube made some VERY important changes to it's api but it has been fixed and has even resolved some problems (Now we can read playlists that are longer than 100) (The home menu can display even more playlists.
