### ISSUE TITLE
File runs from cwd not from the executables directory

### ISSUE THREAD

**Issue by Jaxon-teBoekhorst** [ccgauche/ytermusic#55]
If I have the file in /home/user/.ytermusic, then I add that folder to the PATH, and run it, I get the " The 'headers.txt' file is not present" message, even though the headers.txt file is in the .ytermusic folder and configured properly.

**Comment by ccgauche** [comment]
I'll have to investigate that...

**Comment by ccgauche** [comment]
Should be fixed with #58
