### ISSUE TITLE
Improved Headers File Location: move `headers.txt` file to `XDG_CACHE_HOME` or equivalent 

### ISSUE THREAD

**Issue by lotation** [ccgauche/ytermusic#58]
Currently, the program stores the `headers.txt` header file containing Youtube Music cookie and User Agent in the same directory where the program is executed. I propose moving this header file to a fixed and more appropriate location, such as `XDG_CACHE_HOME` or `$HOME/.cache`. 

This change would enhance program's cleanliness and facilitate packaging for various Linux distributions. While it's not recommended to scatter files needed by programs in random locations (like `/usr/bin` or similar prefixes if using an application launcher) cache directories are designed to cater to such use cases.

Your thoughts on this improvement are welcome.

**Comment by ccgauche** [comment]
I would say editing headers.txt in ~/.cache is not pratical. Moreover, some program tend to delete cache files to get back some disk space. Headers.txt is clearly not some cache but some config.
But I think the idea of having a way to fix the path of headers.txt is a good idea. Maybe even we could have both:
 - It first checks in the current dir then in a ~/.config of  ~/.ytermusic
