### ISSUE TITLE
Downloads do not work anymore

### ISSUE THREAD

**Issue by Alphare** [ccgauche/ytermusic#61]
It's been a few days at least.

The logs say `Error downloading -YXG0fHEFmY: YouTube returned an unexpected response: `watch html did not contain a PlayabilityStatus` [src/tasks/download.rs]` upon failure.

I accidentally removed my `.cache` folder (I'm sad) and now I can't listen to any music. I haven't looked into the change yet.

**Comment by ccgauche** [comment]
Hmmm, youtube seems to have fixed downloading with rustube. I'll check if they found a workaround.

**Comment by MoutonDemocrate** [comment]
Having the same problem, have you found a workaround yet @ccgauche

**Comment by ccgauche** [comment]
I have a solution that I'll be pushing in a few days. The current rustube I'm using is broken I started modding rusty_ytdl to implement it in ytermusic. My PR got merged so it shouldn't take much time now.

**Comment by williamdes** [comment]
Merci !
I just found this project and have the same issue

**Comment by ccgauche** [comment]
Fixed in `beta` branch

**Comment by williamdes** [comment]
> Fixed in `beta` branch

Builds and runs !
🎉 Merci 🙏🏻
