### ISSUE TITLE
[Feature Request] Config to disable volume widget.

### ISSUE THREAD

**Issue by Rustmilian** [ccgauche/ytermusic#65]
While it's useful for Windows, it isn't on Linux as PipeWire already allows for per-application volume control (see below image). The volume slider tui just makes managing audio harder as it's independent from the native audio controller. 
![Screenshot_20231205_182258](https://github.com/ccgauche/ytermusic/assets/110098609/a260f344-9cfe-4735-b584-9a914e94b5a1)

**Comment by Rustmilian** [comment]
```rust
        f.render_widget(
            VerticalGauge::default()
                .block(Block::default().title(" Volume ").borders(Borders::ALL))
                .gauge_style(colors)
                .ratio((self.sink.volume() as f64 / 100.).clamp(0.0, 1.0)),
            volume_rect,
        );
```
https://github.com/ccgauche/ytermusic/blob/master/src/term/music_player.rs#L204-L210

**Comment by ccgauche** [comment]
The volume widget is now opt-out in the config may you check on `beta` branch if it corresponds to what you've been searching for ?

**Comment by Rustmilian** [comment]
@ccgauche I'd check but unfortunately it doesn't seem possible for me to compile on my hardware. If you can compile it for me targeting x86_64 gnu linux, that'd be appreciated.

**Comment by ccgauche** [comment]
No issue I'll have to push the pre-release beta anyways

**Comment by ccgauche** [comment]
A linux x86 build has been added

**Comment by Rustmilian** [comment]
@ccgauche 
![volume-slider-widget](https://github.com/ccgauche/ytermusic/assets/110098609/1a7b5951-4834-40dd-9e7b-75ed02bb0410)
perfect :smile_cat:
