### ISSUE TITLE
[Enhancement] Better text background handling for terminals with transparency. 

### ISSUE THREAD

**Issue by Rustmilian** [ccgauche/ytermusic#66]
I see 3 ways for going about this. 
1. Don't draw the text background at all except for when the selector is hovering on an item.
2. Draw the the text background to the exact character length of the item.
3. Implement some form of transparency configuration option.
![Screenshot_20231205_184845](https://github.com/ccgauche/ytermusic/assets/110098609/f3c139d9-b7a2-4fc5-ae47-1a71520d0646)
![Screenshot_20231205_184005](https://github.com/ccgauche/ytermusic/assets/110098609/f2e0d8b5-6540-4227-bb89-34448758eab2)
![Screenshot_20231205_183400](https://github.com/ccgauche/ytermusic/assets/110098609/7a740d73-8c7d-4b65-8be1-4886c999cce0)

**Comment by ccgauche** [comment]
This has been merged, by default, the background is now transparent and you can edit the default colors in the config.

**Comment by Rustmilian** [comment]
Very nice, thanks. :smile:
