### ISSUE TITLE
Failed to download song

### ISSUE THREAD

**Issue by apolokaklab** [ccgauche/ytermusic#68]
OS: Arch Linux x86_64
DE: Gnome 45
Tested from AUR, binary from release and build from source too.

Failed to download for a song with tag E (explicit), if see on mobile/web.
example song: lily alen - ~~fuck you~~ :sweat_smile:

**Comment by ccgauche** [comment]
I tried a fix on the `beta` branch, would you be able to tell me if it works as expected?
I'm really sorry I wasn't able to work on ytermusic for quite a while.

**Comment by apolokaklab** [comment]
still failed if song have tag E (explicit).
![Screenshot from 2024-02-21 12-29-55](https://github.com/ccgauche/ytermusic/assets/30395693/75223251-355b-4790-ae78-9eedb08a5621)
but other song very fast downloaded.

**Comment by apolokaklab** [comment]
so re-open this issues?
