### ISSUE TITLE
Arch package is already build for this program so you can add this in repo and maybe add steps like where are main files and how to configure it 

### ISSUE THREAD

**Issue by HakaishinShwet** [ccgauche/ytermusic#71]
The `headers.txt` file is not present in the root directory.
To configure the YTerMusic:
1. Open the YouTube Music website in your browser;
2. Open the developer tools (F12);
3. Go to the Network tab;
4. Go to https://music.youtube.com;
5. Copy the `cookie` header from the associated request;
6. Paste it in the `headers.txt` file as `Cookie: <cookie>`;
7. Restart YterMusic

this is shown in terminal

**Comment by HakaishinShwet** [comment]
╰─ where ytermusic                                                                                                                                         ─╯
/usr/bin/ytermusic
/bin/ytermusic
 in /usr/bin ytermuic executable is there but i dont where to create header.txt is it also in /usr/bin or somewhere else?

**Comment by ccgauche** [comment]
It's in ~/.ytermusic or the current working directory. I think I should indeed add the real file path to the help.

**Comment by ccgauche** [comment]
Also note that the AUR is not an official distribution platform that I support so I can't ensure that they are at the lastest version and weren't compromised. The recommended distribution method is GitHub for now. And I recommend you to build the app yourself from the beta branch

**Comment by CarterSnich** [comment]
I just installed `ytermusic-bin` from AUR, it didn't work even it was version `0.1.0-2`. Just change the directory to `~/.ytermusic` then call `ytermusic` (creating an alias would be better). Also, allowing the user to pass an argument to where is `headers.txt` is located would be great.

**Comment by HakaishinShwet** [comment]
yeah i will try to build myself plus will see the directory and test stuff :-))

**Comment by Rustmilian** [comment]
@HakaishinShwet 
@ccgauche 
The AUR package is by me btw.
https://aur.archlinux.org/packages/ytermusic-bin

**Comment by ccgauche** [comment]
> I just installed `ytermusic-bin` from AUR, it didn't work even it was version `0.1.0-2`. Just change the directory to `~/.ytermusic` then call `ytermusic` (creating an alias would be better). Also, allowing the user to pass an argument to where is `headers.txt` is located would be great.

Do you really think it's necessary to be able to change the headers path now that we also check for the config files location of the app ? If so what would be preferred: an ENV variable or a command line argument?

**Comment by Rustmilian** [comment]
@ccgauche I know just the ENV Variable you can follow. `XDG_CONFIG_HOME`.

**Comment by ccgauche** [comment]
> @ccgauche I know just the ENV Variable you can follow. `XDG_CONFIG_HOME`.

It follows this var by default but I think he was searching for a way to only change the headers path maybe to be able to renew it easely

**Comment by ccgauche** [comment]
> @HakaishinShwet 
> The AUR package is by me btw.
> [ytermusic-bin](https://aur.archlinux.org/packages/ytermusic-bin)
> 
> @ccgauche 
> The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ytermusic-bin) is actual really simple and just pulls from [Releases](https://github.com/ccgauche/ytermusic/releases), I created it due to my build issues mentioned previously. You should be able to accept br and logs from it as long as it's up-to-date.
> 
> @CarterSnich
> It wasn't up to the beta, it was still alpha until ~8mins ago.
> It should work now.

That's very nice of you to provide an AUR package!

**Comment by ccgauche** [comment]
> @HakaishinShwet 
> The AUR package is by me btw.
> [ytermusic-bin](https://aur.archlinux.org/packages/ytermusic-bin)
> 
> @ccgauche 
> The [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ytermusic-bin) is actual really simple and just pulls from [Releases](https://github.com/ccgauche/ytermusic/releases), I created it due to my build issues mentioned previously. You should be able to accept br and logs from it as long as it's up-to-date.
> 
> @CarterSnich
> It wasn't up to the beta, it was still alpha until ~8mins ago.
> It should work now.

That's very nice of you to provide an AUR package!

**Comment by Rustmilian** [comment]
> > @ccgauche I know just the ENV Variable you can follow. `XDG_CONFIG_HOME`.
> 
> It follows this var by default but I think he was searching for a way to only change the headers path maybe to be able to renew it easily

I think `$HOME` is already a sufficient location for that purpose tho. Maybe alter it to check `$HOME/.ytermusic` instead so it's in a hidden folder.
