### ISSUE TITLE
Won't detect error when downloading songs

### ISSUE THREAD

**Issue by 7ih** [ccgauche/ytermusic#94]
Windows 11

When a random song has an error when downloading, the program won't detect it or anything so I can't try to redownload the song. If I try to play the song it freezes the terminal. The mp4 of the song will be corrupt in the cache. There's no error in the log file.

**Comment by ccgauche** [comment]
Thanks really strange would you have the corrupted file and/or the video ID?

**Comment by 7ih** [comment]
It's a random song every time,  I think it just doesn't finish downloading
https://github.com/user-attachments/assets/44208582-4c16-467d-8328-109ba8d7387f

**Comment by ccgauche** [comment]
Linked to #95 should be fixed RN
